name: CI

on:
  push:
    branches: master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run rustfmt
        run: cargo fmt --check

  clippy:
      name: Clippy
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Run clippy
          run: cargo clippy -- --deny warnings
